version: '3'

services:
  app:
    container_name: hydra-list
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - hydra-list-data:/data
      - ../.next:/app/.next
      - ../public:/app/public
    environment:
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_APPS_SCRIPT_URL=${GOOGLE_APPS_SCRIPT_URL}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

volumes:
  hydra-list-data:
    # This creates a named volume for persistent data storage